dual_arm:
  rgt_arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - rgt_shoulder_pan_joint
      - rgt_shoulder_lift_joint
      - rgt_elbow_joint
      - rgt_wrist_1_joint
      - rgt_wrist_2_joint
      - rgt_wrist_3_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        rgt_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
        rgt_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
        rgt_elbow_joint: {trajectory: 0.1, goal: 0.1}
        rgt_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
        rgt_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
        rgt_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  lft_arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - lft_shoulder_pan_joint
      - lft_shoulder_lift_joint
      - lft_elbow_joint
      - lft_wrist_1_joint
      - lft_wrist_2_joint
      - lft_wrist_3_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        lft_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
        lft_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
        lft_elbow_joint: {trajectory: 0.1, goal: 0.1}
        lft_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
        lft_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
        lft_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10