controller_manager_ns: controller_manager
controller_list:
  - name: dual_arm/rgt_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rgt_shoulder_pan_joint
      - rgt_shoulder_lift_joint
      - rgt_elbow_joint
      - rgt_wrist_1_joint
      - rgt_wrist_2_joint
      - rgt_wrist_3_joint

  - name: dual_arm/lft_arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - lft_shoulder_pan_joint
      - lft_shoulder_lift_joint
      - lft_elbow_joint
      - lft_wrist_1_joint
      - lft_wrist_2_joint
      - lft_wrist_3_joint

      