# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rgt_arm
  joint_model_group_pose: rgt_zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - rgt_shoulder_pan_joint
    - rgt_shoulder_lift_joint
    - rgt_elbow_joint
    - rgt_wrist_1_joint
    - rgt_wrist_2_joint
    - rgt_wrist_3_joint
    - lft_shoulder_pan_joint
    - lft_shoulder_lift_joint
    - lft_elbow_joint
    - lft_wrist_1_joint
    - lft_wrist_2_joint
    - lft_wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []